### ISSUE TITLE
[Team4] Make testing framework

### ISSUE THREAD

**Issue by eytanadler** [bkochuna/ners570f21-Lab06#28]
Develop a simple testing framework. The testing framework should enable the following:
- [x] Provide general interface to define tests
- [x] Easily run all the tests
- [x] Include templating to switch between single and double precision
- [x] Properly handle errors being thrown while test cases are running
- [x] Handle displaying of results and returning proper value to indicate whether all tests passed or not

**Comment by eytanadler** [comment]
> Note that this testing framework will be executed inside of CTest, which offers some of these capabilities (at least notionally--e.g. printing summary of tests passing/not passing and easily run all the tests). But you may want this capability within each ctest.

Ok I'll take a look; in it's current form it won't work with CTest.

**Comment by bkochuna** [comment]
No need to reinvent the wheel! CTest has a lot of REALLY nice features. I think the main consideration is what granularity do you want for your tests (as defined in CTest). For example, you can have one ctest run a command (potentially with arguments) and that might just verify that constructure/destructor of one class, or it might test all the methods on a class, or you could have a ctest for each "fail" condition (so that you can check your exceptions and asserts are thrown under the correct conditions).

CTests can "pass" when something fails as well. The tests defined within CMake can also be run in parallel (just like you get a parallel build).

Some suggestions:
1. You could write a "test harness" in CPP that takes some command line options so you can define several ctests with minimal CPP coding, but some extra CMake to define each test for a given executable.
2. You can assume a pattern where you have one CTest to one test executable and create a CMake macro that simplifies the CMake you have to write to define the ctest within CMake. (See `<repo>/tests/CMakeLists.txt`) for how this is done.
